name: CI
on:
  push:
    paths-ignore: ['docs/**', '*.md']
  pull_request:
    paths-ignore: ['docs/**', '*.md']
    branches: [master]
  schedule:
    - cron: '0 6 * * 6'
jobs:
  job4:
    name: 'macOS: SFML Homebrew, Crystal Homebrew'
    runs-on: macos-latest
    steps:
      - name: Download CrSFML source
        uses: actions/checkout@v2
      - name: Install SFML
        id: sfml
        uses: oprypin/install-sfml@v1
        with:
          sfml: package
      - run: brew list sfml
      - run: tree /usr/local/Cellar/sfml
      - name: Install Crystal
        run: brew install crystal
      - name: Re-generate sources
        run: crystal generate.cr "${{steps.sfml.outputs.path}}/include"
      - name: Build CrSFML
        run: SFML_INCLUDE_DIR="${{steps.sfml.outputs.path}}/include" make -j
      - name: Generate docs
        run: crystal doc
      - name: Run tests
        run: crystal spec
      - name: Build example "simple"
        working-directory: ./examples
        run: crystal build simple.cr
      - name: Build example "flippy_bird"
        working-directory: ./examples
        run: crystal build flippy_bird.cr
      - name: Build example "snakes"
        working-directory: ./examples
        run: crystal build snakes.cr
      - name: Build example "transformable"
        working-directory: ./examples
        run: crystal build transformable.cr
      - name: Build example "text_input"
        working-directory: ./examples
        run: crystal build text_input.cr
      - name: Build example "diagnostics"
        working-directory: ./examples
        run: crystal build diagnostics.cr
      - name: Build example "sound_capture"
        working-directory: ./examples
        run: crystal build sound_capture.cr
      - name: Build example "shader"
        working-directory: ./examples
        run: crystal build shader.cr
      - name: Build example "shapes"
        working-directory: ./examples
        run: crystal build shapes.cr
      - name: Build example "gl"
        working-directory: ./examples
        run: crystal build gl.cr
      - name: Build example "echo"
        working-directory: ./examples
        run: crystal build echo.cr
      - name: Run example "simple"
        working-directory: ./examples
        run: |
          ./simple & pid=$!
          sleep 3
          kill $pid
      - name: Run example "flippy_bird"
        working-directory: ./examples
        run: |
          ./flippy_bird & pid=$!
          sleep 3
          kill $pid
      - name: Run example "transformable"
        working-directory: ./examples
        run: |
          ./transformable & pid=$!
          sleep 3
          kill $pid
      - name: Run example "text_input"
        working-directory: ./examples
        run: |
          ./text_input & pid=$!
          sleep 3
          kill $pid
      - name: Run example "shader"
        working-directory: ./examples
        run: |
          ./shader & pid=$!
          sleep 3
          kill $pid
      - name: Run example "gl"
        working-directory: ./examples
        run: |
          ./gl & pid=$!
          sleep 3
          kill $pid
